#!/bin/sh

. /etc/rc.d/green_common

log_msg "tftp service $1"

case "${1}" in
	start)
		if [ -z "$HOME" ]; then
                   [ "$USER" ] || USER="$(cat /etc/sysconfig/tcuser)" || USER="tc"
                   HOME=/home/"$USER"
                fi
		/sbin/udpsvd -E 0 69 tftpd $HOME &
		;;

	stop)
		pkill udpsvd
		;;

	status)
		pidof udpsvd
		;;

	*)
		exit 1
		;;
esac
