#!/bin/sh
# docker daemon start script
[ $(id -u) = 0 ] || { echo 'must be root' ; exit 1; }

BOOT_DIR=/opt/boot
DOCKER_PID=/var/run/docker.pid

if [ ! -e $BOOT_DIR/etc/profile ]
then
  echo "# put docker settings here e.g. HTTP_PROXY, HTTPS_PROXY, DOCKER_STORAGE, DOCKER_LOGFILE, CERT_INTERFACES, CERT_DIR" > $BOOT_DIR/etc/profile
fi

. $BOOT_DIR/etc/profile

: ${DOCKER_HOST:='-H tcp://0.0.0.0:2375'}
: ${DOCKER_TLS:=auto}

if [ -e /dev/zvol/green/docker_vol ] ; then
: ${DOCKER_STORAGE:=overlay}
else
: ${DOCKER_STORAGE:=zfs}
fi

: ${DOCKER_DIR:=/var/lib/docker}
: ${DOCKER_ULIMITS:=1048576}
: ${DOCKER_LOGFILE:=$BOOT_DIR/log/docker.log}

: ${CERT_DIR:=$BOOT_DIR/tls/}
: ${CERT_INTERFACES:='eth0 eth1'}
: ${CA_CERT:="${CERT_DIR}ca.pem"}
: ${CA_KEY:="${CERT_DIR}cakey.pem"}
: ${SERVER_CERT:="${CERT_DIR}server.pem"}
: ${SERVER_KEY:="${CERT_DIR}serverkey.pem"}
: ${CERT:="${CERT_DIR}cert.pem"}
: ${KEY:="${CERT_DIR}key.pem"}

start() {
    # Not enabling Docker daemon TLS by default.
    if [ "$DOCKER_TLS" != "no" ]; then
        CERTHOSTNAMES="$(hostname -s),$(hostname -i)"
        for interface in ${CERT_INTERFACES}; do
          IP=$(ip addr show ${interface} |sed -nEe 's/^[ \t]*inet[ \t]*([0-9.]+)\/.*$/\1/p')
          if [ "$IP" != "" ]; then
            CERTHOSTNAMES="$CERTHOSTNAMES,$IP"
          fi
        done
        echo "Need TLS certs for $CERTHOSTNAMES"
        echo "-------------------"

        mkdir -p "$CERT_DIR"
        chmod 700 "$CERT_DIR"
        if [ ! -f "$CA_CERT" ] || [ ! -f "$CA_KEY" ]; then
            echo "Generating CA cert"
            /usr/local/bin/generate_cert --cert="$CA_CERT" --key="$CA_KEY"
            rm "$SERVER_CERT" "$SERVER_KEY" "$CERT" "$KEY" "$CERT_DIR/hostnames"
        fi

        CERTSEXISTFOR=$(cat "$CERT_DIR/hostnames" 2>/dev/null)
        if [ "$CERTHOSTNAMES" != "$CERTSEXISTFOR" ]; then
            echo "Generate server cert"
            echo /usr/local/bin/generate_cert --host="$CERTHOSTNAMES" --ca="$CA_CERT" --ca-key="$CA_KEY" --cert="$SERVER_CERT" --key="$SERVER_KEY"
            /usr/local/bin/generate_cert --host="$CERTHOSTNAMES" --ca="$CA_CERT" --ca-key="$CA_KEY" --cert="$SERVER_CERT" --key="$SERVER_KEY"
            echo "$CERTHOSTNAMES" > "$CERT_DIR/hostnames"
        fi

        if [ ! -f "$CERT" ] || [ ! -f "$KEY" ]; then
            echo "Generating client cert"
            /usr/local/bin/generate_cert --ca="$CA_CERT" --ca-key="$CA_KEY" --cert="$CERT" --key="$KEY"
        fi

        if [ "$DOCKER_TLS" == "auto" ]; then
            DOCKER_HOST='-H tcp://0.0.0.0:2376'
            EXTRA_ARGS="$EXTRA_ARGS --tlsverify --tlscacert=$CA_CERT --tlscert=$SERVER_CERT --tlskey=$SERVER_KEY"
        elif [ "$DOCKER_TLS" != "no" ]; then
            EXTRA_ARGS="$EXTRA_ARGS $DOCKER_TLS --tlscacert=$CA_CERT --tlscert=$SERVER_CERT --tlskey=$SERVER_KEY"
        fi

        # now make the client certificates available to the docker user
        USERCFG="/home/docker/.docker"
        mkdir -p "$USERCFG"
        chmod 700 "$USERCFG"
        cp "$CA_CERT" "$USERCFG"
        cp "$CERT" "$USERCFG"
        cp "$KEY" "$USERCFG"
        chown -R docker:staff "$USERCFG"
    fi

    mkdir -p "$DOCKER_DIR"

    if [ "$DOCKER_STORAGE" = 'auto' ]; then
        # if /var/lib/docker is on BTRFS, let's use the native btrfs driver
        # (AUFS on top of BTRFS does very bad things)
        DOCKER_DEVICE="$(/bin/df -P "$DOCKER_DIR" | /usr/bin/awk 'END { print $1 }')"
        DOCKER_FSTYPE="$(/sbin/blkid -o export "$DOCKER_DEVICE" | /bin/grep TYPE= | /usr/bin/cut -d= -f2)"
        if [ "$DOCKER_FSTYPE" = 'btrfs' ]; then
            DOCKER_STORAGE="$DOCKER_FSTYPE"
        fi
    fi
    if [ "$DOCKER_STORAGE" != 'auto' ]; then
        # in the general case, let's trust Docker to "do the right thing"
        EXTRA_ARGS="$EXTRA_ARGS --storage-driver=$DOCKER_STORAGE"
    fi

    # Increasing the number of open files and processes by docker
    ulimit -n $DOCKER_ULIMITS
    ulimit -p $DOCKER_ULIMITS

    echo /usr/local/bin/docker daemon --debug=false --graph=$DOCKER_DIR -H unix:// $DOCKER_HOST $EXTRA_ARGS  >> $DOCKER_LOGFILE
    /usr/local/bin/docker daemon --debug=false --graph=$DOCKER_DIR -H unix:// $DOCKER_HOST $EXTRA_ARGS >> $DOCKER_LOGFILE 2>&1 &
}

stop() {
    kill $(cat $DOCKER_PID)
}

restart() {
    if check; then
        stop && sleep 1 && start
    else
        start
    fi
}

check() {
    [ -f $DOCKER_PID ] && ps $(cat $DOCKER_PID) > /dev/null 2>&1
}

status() {
    if check; then
        echo 'Docker daemon is running'
        exit 0
    else
        echo 'Docker daemon is not running'
        exit 1
    fi
}

case $1 in
    start) start;;
    stop) stop;;
    restart) restart;;
    status) status;;
    *) echo "Usage $0 {start|stop|restart|status}"; exit 1
esac
