#!/bin/sh
echo "automount zfs ...";

modprobe zfs
umount /var/lib/docker/aufs
killall docker
mv /var/lib/docker /var/lib/docker.orig
zpool import green

swapon /dev/zvol/green/swap 
swapoff /dev/zram0

echo "automount over."
