#!/bin/sh

. /etc/green_common

: ${CROND_LOGLEVEL:=8}

CMD=$1
if [ -z ${CMD} ] ; then
   CMD=start
fi

case "${CMD}" in
	start)
    log_msg "start crond"
		crond -f -d "$CROND_LOGLEVEL" > $BOOT_DIR/log/crond.log 2>&1 &
		;;

	stop)
		pkill crond
		;;

	status)
		pidof -o %PPID crond
		;;

	*)
		exit 1
		;;
esac
