#!/bin/bash
. /etc/green_common

COREFILE=/etc/dns/Corefile

if [ ! -f /opt/apps/green/bin/coredns ] ; then
  log_msg "no coredns execute" R
  exit 0
fi
if [ ! -f $COREFILE ] ; then
  log_msg "no coredns config" R
  exit 0
fi

if /bin/ps ax | grep "coredns.*Corefile" | grep -v grep ; then
   killall coredns
fi

if ! touch $BOOT_DIR/log/coredns.log ; then
  # $BOOT_DIR/log not writeable
  sed -i -e 's/ log / #log /' $COREFILE
  sed -i -e 's/ errors / #errors /' $COREFILE
else
  sed -i -e 's/ #log / log /' $COREFILE
  sed -i -e 's/ #errors / errors /' $COREFILE
fi

log_msg "start coredns /etc/Corefile" M
/opt/apps/green/bin/coredns -conf $COREFILE &
