#!/bin/bash

. /etc/green_common

log_msg "iptables firewall start" B
if [ -z "$FIREWALL" ] ; then
   exit 0
fi

# https://strongarm.io/blog/linux-stateless-firewall/

iptables -F INPUT
iptables -F OUTPUT

# Stateless firewall!
iptables -t raw -I PREROUTING -j NOTRACK
iptables -t raw -I OUTPUT -j NOTRACK

# Allow any established connections, dropping everything else
iptables -A INPUT -p tcp ! --syn -j ACCEPT
iptables -A OUTPUT -p tcp ! --syn -j ACCEPT

iptables -P INPUT DROP
iptables -P OUTPUT DROP
iptables -A INPUT  -i lo -j ACCEPT
iptables -A OUTPUT -o lo -j ACCEPT

iptables -A INPUT -p icmp --icmp-type destination-unreachable -j ACCEPT # icmp routing messages
#iptables -A OUTPUT -p icmp --icmp-type echo-request -j ACCEPT
iptables -A OUTPUT -p icmp -j ACCEPT
iptables -A INPUT -p icmp --icmp-type echo-reply -j ACCEPT

if [ -z "$FIREWALL_FWKNOP" ] ; then
  iptables -I INPUT -p tcp --dport 22 -j ACCEPT # ssh
  iptables -I INPUT -p tcp --dport 80 -j ACCEPT # http
  iptables -I INPUT -p tcp --dport 443 -j ACCEPT # https
fi

iptables -I OUTPUT -p tcp --dport 22 -j ACCEPT # ssh
iptables -I OUTPUT -p tcp --dport 80 -j ACCEPT # http
iptables -I OUTPUT -p tcp --dport 443 -j ACCEPT # https

# Allow DNS lookups to be initiated from this server
iptables -A OUTPUT -p udp --dport 53 -j ACCEPT # dns
iptables -A OUTPUT -p tcp --dport 53 -j ACCEPT # dns
iptables -A INPUT -p udp --sport 53 -j ACCEPT # dns responses


#iptables -F

#iptables -F INPUT
#iptables --policy INPUT ACCEPT
#iptables -I INPUT 1 -i $INTERFACE -p tcp --dport 22 -j DROP
#iptables -I INPUT 1 -i $INTERFACE -p tcp --dport 22 -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

#iptables -I INPUT 1 -i $INTERFACE -p udp --dport 53 -j DROP
#iptables -I INPUT 1 -i $INTERFACE -p udp --dport 53 -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

#iptables -I INPUT 1 -i $INTERFACE -p tcp --dport 53 -j DROP
#iptables -I INPUT 1 -i $INTERFACE -p tcp --dport 53 -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

#iptables -I INPUT 1 -i $INTERFACE -p tcp --dport 80 -j DROP
#iptables -I INPUT 1 -i $INTERFACE -p tcp --dport 80 -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

#iptables -F FORWARD
#iptables --policy FORWARD ACCEPT

#iptables --policy FORWARD DROP
#iptables --policy FORWARD DROP
#iptables -F DOCKER
#iptables -I DOCKER 1 -i $INTERFACE -p tcp --dport 80 -j DROP
#iptables -I DOCKER 1 -i $INTERFACE -p tcp --dport 80 -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

if ! which fwknop || [ -z "$FIREWALL_FWKNOP" ] ; then
   exit 0
fi


INTERFACE=$FIREWALL_FWKNOP
log_msg "iptables firewall/fwknop start on $INTERFACE" B

fwknopd --kill

[ -d $BOOT_DIR/etc/fwknop ] || mkdir $BOOT_DIR/etc/fwknop

FILE=$BOOT_DIR/etc/fwknop/fwknopd.conf

if [ ! -f $FILE ] ; then

cat > $FILE <<EOF
FWKNOP_CONF_DIR    $BOOT_DIR/etc/fwknop;
FIREWALL_EXE   /usr/local/sbin/iptables;
EOF

FILE=$BOOT_DIR/etc/fwknop/access.conf
cat > $FILE <<EOF
SOURCE                     ANY
OPEN_PORTS                 tcp/22,tcp/80,udp/53,tcp/53
REQUIRE_SOURCE_ADDRESS     N
REQUIRE_USERNAME           greenbox
FW_ACCESS_TIMEOUT          86400
EOF
fwknop -k -s >> $FILE

chmod 0600 $BOOT_DIR/etc/fwknop/*.conf

fi

fwknopd -i $INTERFACE \
   --syslog-enable \
   --config-file $BOOT_DIR/etc/fwknop/fwknopd.conf \
   --access-file $BOOT_DIR/etc/fwknop/access.conf
