#!/bin/bash

. /etc/green_common

[ -z "$PROXY" ] && exit 0

log_msg "start squid/squidGuard proxy"

[ -d $BOOT_DIR/proxy ] || mkdir $BOOT_DIR/proxy

cd $BOOT_DIR/proxy

#if [ ! -f shallalist.tar.gz ] ; then
#   curl $CURL_OPTS -LO http://www.shallalist.de/Downloads/shallalist.tar.gz
#   tar xf shallalist.tar.gz
#fi

if [ ! -f shallalist.tar.gz ] ; then
   curl $CURL_OPTS -LO http://www.shallalist.de/Downloads/shallalist.tar.gz
   # http://download.bring.out.ba/blacklist.tar.bz2
   tar xf shallalist.tar.gz
fi

if [ ! -f additionalBlackDomains ] ; then
cat > additionalBlackDomains <<EOF
jwpltx.com
camsareonline.com
click.hookupcams.com
trcktm.net
toppharm.biz
diane-with-victoria.us
andrea-with-debra.us
dating510.com
selfsend.ru
verifiedtrader.co
l0tt0crusher.com
fast4diets.com
EOF
fi


. /etc/green_docker_service_common

docker rm -f proxy

#-e UPDATE_BLACKLIST_URL=http://www.shallalist.de/Downloads/shallalist.tar.gz \
#	-e WPAD_IP=192.168.168.101 \
#	-e WPAD_NOPROXY_NET=192.168.168.0 \
# -e WPAD_NOPROXY_MASK=255.255.255.0 \
#--publish 80:80 \

docker run --name proxy \
    -d \
    --network=host \
    --restart=always \
    -e SQUID_CONFIG_SOURCE=/etc/proxy \
    --volume /etc/proxy:/etc/proxy \
    -v /etc/proxy/squid.conf:/etc/squid3/squid.conf \
    -v $BOOT_DIR/proxy/additionalBlackDomains:/etc/proxy/additionalBlackDomains \
    -v $BOOT_DIR/proxy/cache:/var/spool/squid3 \
    -v $BOOT_DIR/proxy/BL:/var/lib/squidguard/db/BL \
    --publish 3128:3128 \
    muenchhausen/docker-squidguard:latest
