#!/bin/sh

. /etc/green_common

if ( ! scaleway_server )
then
   echo "this is not scaleway server"
   exit 0
fi

# https://community.online.net/t/openbsd-on-a-vc1/1933

if ! curl http://$SCALEWAY_SIGNAL_SERVER/state -X PATCH -H 'Content-Type: application/json' -d '{"state_detail": "booted"}'
then
  echo "${RED}SCALEWAY Signalink server $SCALEWAY_SIGNAL_SERVER ERROR${NORMAL}"
else
  echo "${GREEN}SCALEWAY Signalink server booted OK${NORMAL}"
fi
