#!/bin/sh

. /etc/green_common

if ps ax | grep -q sshd$ ; then
   echo sshd already launched
   exit 0
fi

log_msg "start openssh server"

# Configure sshd and acknowledge for persistence in $BOOT_DIR of the keys/config
# Move /usr/local/etc/ssh to $BOOT_DIR/ssh if it doesn't exist
if [ ! -d $BOOT_DIR/ssh ]; then
    mv /usr/local/etc/ssh $BOOT_DIR/
else # if it exists, remove the ramdisk's ssh config, so that the hard drive's is properly linked
    rm -rf /usr/local/etc/ssh
fi
ln -s $BOOT_DIR/ssh /usr/local/etc/ssh

if ! grep -q "^UseDNS no" /usr/local/etc/ssh/sshd_config; then
    # speed up login
    echo "UseDNS no" >> /usr/local/etc/ssh/sshd_config
fi

if ! grep -q "^Subsystem .*sftp" /usr/local/etc/ssh/sshd_config; then
    # ansible needs sftp
    echo "Subsystem  sftp  /usr/local/lib/openssh/sftp-server" >> /usr/local/etc/ssh/sshd_config
fi

[ -d /var/ssh ] || mkdir -p /var/ssh

case $1 in
   restart) /usr/local/etc/init.d/openssh restart;;
   *) /usr/local/etc/init.d/openssh start
esac
