#!/bin/sh

. /etc/green_common

[ -f /opt/boot/init.d/nodockerstart ] && log_msg "nodockerstart SET - stop!" && exit 1

/usr/local/etc/init.d/docker start

log_msg "starting $BOOT_DIR/init.d scripts ..."
[ ! -d $BOOT_DIR/init.d ] && mkdir -p $BOOT_DIR/init.d &&\
(cat  > $BOOT_DIR/init.d/00_test.sh <<- EOF
echo "#!/bin/sh"
. /etc/green_service_common
log_msg "test service PATH: \$PATH, LD_LIBRARY_PATH: \$LD_LIBRARY_PATH  docker: \`docker --version\`"

set | grep _VER | xargs echo | tee -a \$LOG_FILE
EOF
) && chmod +x $BOOT_DIR/init.d/00_test.sh


cd $BOOT_DIR/init.d   && ls -1 *.sh | xargs -I %  sh -c "$BOOT_DIR/init.d/%&"
