#!/bin/sh

. /etc/green_common
log_msg "tce-loader START (/usr/local/tce.installed) "

for prog in $(find /usr/local/tce.installed/ -type f)
do
  log_msg "running: $prog"
  echo $prog
  sh -c $prog
done
