#!/bin/sh

. /etc/green_common

log_msg "Loading virtualbox server kernel drivers"

if ( is_vbox )
then
 modprobe vboxguest
 modprobe vboxsf
else
 modprobe vboxdrv
 modprobe vboxnetadp
 modprobe vboxnetflt
 modprobe vboxpci
fi
