#!/bin/sh

. /etc/green_common

if ( ! is_vbox ) && ( ! scaleway_virtual_server )
then
 log_msg "Loading virtualbox host server kernel drivers"
 modprobe vboxdrv
 modprobe vboxnetadp
 modprobe vboxnetflt
 modprobe vboxpci
fi
