#!/bin/sh
# Copyright 2011 Canonical, Inc
#           2014 Tianon Gravi
# Author: Serge Hallyn <serge.hallyn@canonical.com>
#         Tianon Gravi <admwiggin@gmail.com>

. /etc/green_common

log_msg "mount cgroups hierarchy"

#set -e

# doh, TCL doesn't have "mountpoint"
mountpoint() {
	dashQ=$1
	dir=$(readlink -f "$2")
	grep -q " $dir " /proc/mounts
}

# for simplicity this script provides no flexibility

# if cgroup is mounted by fstab, don't run
# don't get too smart - bail on any uncommented entry with 'cgroup' in it
if grep -v '^#' /etc/fstab | grep -q cgroup; then
	log_msg 'cgroups mounted from fstab, not mounting /sys/fs/cgroup' R
	exit 1
fi


if [ ! -e /proc/cgroups ]; then
	log_msg "kernel doesn't provides cgroups!?, not mounting /sys/fs/cgroup" R
	exit 1
fi

if [ ! -d /sys/fs/cgroup ]; then
	log_msg "No directory /sys/fs/cgroup ERROR" R
	exit 1
fi

# mount /sys/fs/cgroup if not already done
if ! mountpoint -q /sys/fs/cgroup; then
	    /bin/mount -t tmpfs -o uid=0,gid=0,mode=0755 cgroup /sys/fs/cgroup
			log_msg  "mounting /sys/fs/cgroup on tmpfs ($?)" G
fi

log_msg "----- /proc/cgroups: -----" M
cat /proc/cgroups
cat /proc/cgroups >> $LOG_FILE

cd /sys/fs/cgroup
for sys in $(/usr/bin/awk '!/^#/ { if ($4 == 1) print $1 }' /proc/cgroups); do
	mkdir -p $sys
	if ! mountpoint -q $sys; then
		  if ! /bin/mount -n -t cgroup -o $sys cgroup $sys; then
				 log_msg "ERROR mounting cgroup controller $sys" R
			   rmdir $sys || true
      else
				 log_msg "mounting cgroup controller $sys" G
			fi
	fi
done

# example /proc/cgroups:
#  #subsys_name	hierarchy	num_cgroups	enabled
#  cpuset	2	3	1
#  cpu	3	3	1
#  cpuacct	4	3	1
#  memory	5	3	0
#  devices	6	3	1
#  freezer	7	3	1
#  blkio	8	3	1

exit 0
