#!/bin/sh

DATE=`date +'%Y%m%d %T'`

KERNEL_VERSION=`uname -r | sed -e 's/-greenbox//'`
DOCKER_VERSION=`cat /etc/sysconfig/docker`

GREEN_APPS_VER=2.0.0
X11_APPS_VER=3.1.0
VBOX_VER=5.1.8
VAGRANT_VER=1.8.6
VIM_VER=8.0.5
PYTHON2_VER=2.7.12
RUBY_VER=2.3.1

GO_VER=1.7.3
NODE_VER=6.9.1
PERL_VER=5.22.1
JAVA_VER=8.112.15
IDEA_VER=2016.5.2
ATOM_VER=1.11.2
CODE_VER=1.7.1


BOOT_DIR=/opt/boot

set_log_file() {
[ -f /opt/boot/etc/profile ] && source /opt/boot/etc/profile

if [ -d /opt/boot/log ]
then
  LOG_FILE=/var/log/greenbox.log
else
  LOG_FILE=/var/log/greenbox_0.log
fi

export LOG_FILE
}


log_msg() {
  echo "$0 $DATE: $1" >> $LOG_FILE
}

mountedOnGreen() {
  (cat /proc/mounts | grep -q "^green/$1")
}

mountedApp() {
  (cat /proc/mounts | grep -q "opt_apps /opt/$1")
}

mount_bind_opt_apps() {

if [ -d /opt/apps/$1 ] ; then
  if ! $(grep -q \/opt\/$1 /proc/mounts) ; then
    echo mkdir, mount /opt/apps/$1 ...
    sudo mkdir -p /opt/$1
    sudo mount --bind /opt/apps/$1 /opt/$1 >> $LOG_FILE
    log_msg "/opt/$1 bind mounted"
  fi
fi

}

umount_opt() {

if [ -d /opt/apps/$1 ] ; then
  if  $(grep -q \/opt\/$1 /proc/mounts) ; then
    sudo umount -f -l /opt/$1 >> $LOG_FILE
  fi
fi

}

mount_all_apps() {

for app in `ls -1 /opt/apps`
do
   [ -d /opt/apps/${app} ] && ( ! mountedApp ${app} ) && mount_bind_opt_apps ${app}
done

}

zfs_up() {
  zfs list | grep -q green
}

is_vbox () {
  lshw | grep -q "product: VirtualBox"
}


wait_zvol_up () {

retry=0
while [ ! -e /dev/zvol/$1/$2 ] &&  [ $retry -lt 12 ]
do
   log_msg "waiting zvol $retry $1 $2 up"
   sleep 1
   let retry=retry+1
done

}


set_path_ld_library() {

LD_LIBRARY_PATH=/usr/local/lib:/usr/lib:/lib

for appdir in `ls -1 /opt`
do
   if [ -d /opt/$appdir/lib ] ; then
      LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/$appdir/lib
   fi

   if [ -d /opt/$appdir/bin ] ; then
      PATH=/opt/$appdir/bin:$PATH
   else
      if  [ -d /opt/$appdir ] && [ "$appdir" != "apps" ] && [ "$appdir" != "boot" ] ; then
         export PATH=/opt/$appdir:$PATH
      fi
   fi
done
}

change_user_password() {
   echo "$1:$2" | chpasswd -m
}

vbox_fix_permissions() {
  VBOX_DIR=/opt/apps/VirtualBox
  if [ -d $VBOX_DIR ] ; then
    # VirtualBox execs has to be root
    [ "rootroox" == `ls -ld $VBOX_DIR | awk '{print $3 $4;}'` ] || \
       chown root:root -R $VBOX_DIR
    chmod u+s $VBOX_DIR/VirtualBox $BOX_DIR/VBoxHeadless
    chmod g-w /opt
    chmod g-w /opt/VirtualBox
  fi
}

GREEN_DEBUG=${GREEN_DEBUG:-1}
set_log_file
