#!/bin/sh

. /etc/green_common
. /etc/init.d/tc-functions

set_path_ld_library


log_msg "START: $0"

while ! curl -s --connect-timeout 10 --unix-socket /var/run/docker.sock http:/_ping | grep -q OK ; do
   log_msg "waiting for dockerd"
   sleep 30
done


docker_run() {
  (docker run $1 2>&1) >> $LOG_FILE
}
