#!/bin/sh

# Set hostname
# Originally a function contributed by henk.1955
# Now callable via /opt/bootsync.sh when no boot host= is specified.

. /etc/green_common

useBusybox
HOSTNAME="$(getbootparam host 2>/dev/null)"
[ -n "$HOSTNAME" ] || HOSTNAME="$1"
[ -n "$HOSTNAME" ] || HOSTNAME="box"

if [ ! -e $BOOT_DIR/etc/hostname ]; then
    cp /usr/local/etc/hostname $BOOT_DIR/etc/hostname
fi
HOSTNAME=`cat $BOOT_DIR/etc/hostname`

log_msg "Setting hostname to $HOSTNAME" M

rm -f /etc/hostname
echo $HOSTNAME >/etc/hostname
hostname -F /etc/hostname
rm -f /etc/hosts
cat >/etc/hosts <<EOT
127.0.0.1 $HOSTNAME localhost localhost.local
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
EOT

echo "${GREEN}Done.${NORMAL}"
