#!/bin/busybox ash

# RC Script for Tiny Core Linux
# (c) Robert Shingledecker 2004-2012
# Several modifications for speed by Curaga

. /etc/green_common

log_msg "==== start $0, called by /etc/init.d/rcS =====" B

useBusybox

TCEDIR="/tmp/tce"
TCEOPT="/tmp/tce/optional"
TCLOOP="/tmp/tcloop"
TCEINSTALLED="/usr/local/tce.installed"
INSTALLED=""
VERSION="$(cat /usr/share/doc/tc/release.txt)"
KERNEL="$(uname -r)"

addUser() {
	echo "${GREEN}Adding user ${YELLOW}docker ${NORMAL}"
	/bin/adduser -s /bin/bash -G staff -D docker
	[ -n "$DOCKER_PASSWORD" ] && change_user_password docker $DOCKER_PASSWORD
	echo -e "docker\tALL=NOPASSWD: ALL" >> /etc/sudoers
}

### END functions

# Main

clear
echo "${GREEN}Booting greenbox ${YELLOW}Core $VERSION ${NORMAL}"
echo "${GREEN}Running Linux Kernel ${YELLOW}$KERNEL${GREEN}.${NORMAL}"

log_msg "set PATH /usr/local/sbin,bin etc ..."
PATH=/usr/local/sbin:/usr/local/bin:/bin:/sbin:/usr/bin:/usr/sbin

log_msg "Here we check all the boot parameters using the fastest way known to men, case & loop"
echo -n "${BLUE}Checking boot options...${NORMAL}"
for i in `cat /proc/cmdline`; do
	case $i in
		*=*)
			case $i in
				waitusb*) WAITUSB=${i#*=} ;;
				lang=*) LANGUAGE=${i#*=} ;;
				kmap*) KEYMAP=${i#*=} ;;
				tz=*) TZ=${i#*=} ;;
				staticip=*) STATICIPADDRESS=${i#*=} ;;
				staticiface=*) STATICIFACE=${i#*=} ;;
				ntpserver=*) NTPSERVER=${i#*=} ;;
				dockerpwd=*) DOCKER_PASSWORD=${i#*=} ;;
				rootpwd=*) ROOT_PASSWORD=${i#*=} ;;
				#host=*) HOST=1 ;;
				#nfsmount=* ) NFSMOUNT=${i#*=} ;;
				#nbd=* ) NBD=${i#*=} ;;
				#pretce=* ) PRETCE=${i#*=} ;;
				xvesa=* ) XVESA=${i#*=} ;;
				rsyslog=* ) RSYSLOG=${i#*=}; SYSLOG=1 ;;
				blacklist=* ) BLACKLIST="$BLACKLIST ${i#*=}" ;;
			esac
		;;
		*)
			case $i in
				nodockerstart) NODOCKERSTART=1 ;;
				nortc) NORTC=1 ;;
				syslog) SYSLOG=1 ;;
				noutc) NOUTC=1 ;;
				nodhcp) NODHCP=1 ;;
				superuser) SUPERUSER=1 ;;
				#laptop) LAPTOP=1 ;;
				base) ONLYBASE=1 ;;
				showapps) SHOWAPPS=1 ;;
				norestore) NORESTORE=1 ;;
				noautologin) NOAUTOLOGIN=1 ;;
			esac
		;;
	esac
done
echo "${GREEN} Done.${NORMAL}"

log_msg "blacklist: $BLACKLIST"

if [ -n "$BLACKLIST" ]; then
	mkdir -p /etc/modprobe.d
	for i in $BLACKLIST; do
		echo "$i" | tr ',' '\n' | while read j ; do
			echo "blacklist $j" >> /etc/modprobe.d/blacklist.conf
		done
	done
fi

log_msg "Start udev daemon to populate /dev and handle hotplug events" B
/sbin/udevd --daemon 2>&1 >/dev/null
/sbin/udevadm trigger --action=add 2>&1 >/dev/null &
rotdash $!
echo "${GREEN} Done.${NORMAL}"

[ -n "$WAITUSB" ] && (
	case $WAITUSB in
		*:*) dev=${WAITUSB#*:}
		timeout=$((${WAITUSB%:*} * 4))
		while [ $timeout -gt 0 ]; do
			echo -en "${BLUE}\rWaiting as requested... ${NORMAL}$(($timeout / 4)) "
			timeout=$(($timeout - 1))
			sleep 0.25
			blkid -lt $dev >/dev/null && timeout=0
		done
		echo
		;;
		*) sleep "$WAITUSB" ;;
	esac
)

modprobe loop 2>/dev/null
#modprobe ohci_hcd

#echo "${BLUE}Scanning hard disk partitions to create ${YELLOW}/etc/fstab ${NORMAL}"
#/usr/sbin/rebuildfstab & fstab_pid=$!

mv /tmp/98-tc.rules /etc/udev/rules.d/. 2>/dev/null
/sbin/udevadm control --reload-rules &

if [ -n "$SYSLOG" ]; then
	 [ -z "$RSYSLOG" ] || SOPTS=" -L -R $RSYSLOG "
	 /sbin/syslogd ${SOPTS} && echo "${GREEN}syslog started.${NORMAL}"
	 /sbin/klogd && echo "${GREEN}klog started."
fi

[ -n "$LANGUAGE" ] || LANGUAGE="C"
log_msg "Setting Language to $LANGUAGE" B
echo "LANG=$LANGUAGE" > /etc/sysconfig/language
export LANG=$LANGUAGE

echo "${GREEN} Done.${NORMAL}"

if [ -n "$TZ" ]; then
	echo -n "${GREEN}Setting Timezone to ${MAGENTA}$TZ"
	export TZ && echo "TZ=$TZ" > /etc/sysconfig/timezone
	echo "${GREEN} Done.${NORMAL}"
fi

if [ -n "$NORTC" ]; then
	log_msg "Skipping rtc as requested from the boot command line" B
else
	while [ ! -e /dev/rtc0 ]; do usleep 50000; done
	if [ -n "$NOUTC" ]; then
		hwclock -l -s &
	else
		hwclock -u -s &
	fi
fi



log_msg "config 127.0.0.1"
/sbin/ifconfig lo 127.0.0.1 up
/sbin/route add 127.0.0.1 lo &

if [ -n "$STATICIPADDRESS" ]; then
  if [ -z "$STATICIFACE" ]; then
      STATICIFACE=eth0
  fi
	ifconfig $STATICIFACE $STATICIPADDRESS up
  NODHCP=1
	log_msg "Static ip address: $STATICIFACE / $STATICIPADDRESS" B
fi

wait4Server() {
  log_msg "dhcp.sh runs udhcpc async, so it exits before network is up"
	/etc/init.d/dhcp.sh
	SERVER=$1 ; NOPING=$2 ; CNT=0
	if [ "$NOPING" == "1" ] ; then
		until ifconfig | grep -q Bcast
		do
			[ $((CNT++)) -gt 60 ] && break || sleep 1
		done
		sleep 1
	else
		until ping -c 1 $SERVER >/dev/null 2>&1
		do
			[ $((CNT++)) -gt 60 ] && break || sleep 1
		done
	fi
	DHCP_RAN=1
}


if ! grep -q "^docker" /etc/passwd &>/dev/null; then addUser; fi

echo "docker" > /etc/sysconfig/tcuser
mkdir -p ${DOCKER_HOME_DIR}

if [ -n "$SUPERUSER" ]; then
	touch /etc/sysconfig/superuser
fi

#/etc/rc.d/server_scaleway
#/etc/rc.d/server_vultr

log_msg "Setup base directories for TCE Applicatons"
[ -d "$TCEINSTALLED" ] || mkdir "$TCEINSTALLED"
[ -d "$TCEDIR" ] || mkdir "$TCEDIR"
[ -d "$TCEOPT" ] || mkdir "$TCEOPT"
[ -d "$TCLOOP" ] || mkdir "$TCLOOP"
ln -sf "$TCEDIR" /etc/sysconfig/tcedir
chown docker "$TCEOPT"
chgrp staff "$TCEDIR" "$TCEOPT" "$TCEINSTALLED" "$TCLOOP"
chmod g+w "$TCEDIR" "$TCEOPT" "$TCEINSTALLED" "$TCLOOP"

chmod u+s /bin/busybox.suid /usr/bin/sudo


[ -n "$KEYMAP" ] || KEYMAP="us"
if [ -f "/usr/share/kmap/$KEYMAP.kmap" ]; then
	echo -n "${GREEN}Setting keymap to ${MAGENTA}$KEYMAP"
	/sbin/loadkmap < /usr/share/kmap/$KEYMAP.kmap
	echo "KEYMAP=$KEYMAP" > /etc/sysconfig/keymap
	echo "${GREEN} Done.${NORMAL}"
fi

if [ -n "$ROOT_PASSWORD" ]; then
	echo "root:$ROOT_PASSWORD" | chpasswd -m
fi

[ -n "$XVESA" ]  && sed -i 's/1024x768x32/'"$XVESA"'/' ${DOCKER_HOME_DIR}/.xsession 2>/dev/null

log_msg "If ntpserver: $NTPSERVER is specified use that"
if [ -n "$NTPSERVER" ]; then
	echo "$NTPSERVER" > /etc/sysconfig/ntpserver
else
	[ -s /etc/sysconfig/ntpserver ] && NTPSERVER=`cat /etc/sysconfig/ntpserver`
fi

#if [ -n "$NORESTORE" ]; then
#	echo "${GREEN}Skipping restore as requested from the command line.${NORMAL}"
#else
#	TCEDIR=`readlink /etc/sysconfig/tcedir`
#	/etc/init.d/tc-restore.sh "$TCEDIR"
#fi

# After restore items
if [ -n "$NODHCP" ]; then
	echo "${GREEN}Skipping DHCP broadcast/network detection as requested on boot commandline.${NORMAL}"
else
	[ -z "$DHCP_RAN" ] && /etc/init.d/dhcp.sh &
	[ -z "$NORTC" ] || /etc/init.d/settime.sh &
fi

/sbin/loadcpufreq 2>/dev/null &

[ -n "$NODOCKERSTART" ] && touch $BOOT_DIR/init.d/nodockerstart
[ -n "$NOAUTOLOGIN" ] && echo "booting" > /etc/sysconfig/noautologin


/opt/bootscript.sh
